Dev update docs
revisit-studies/reVISit-studies.github.io pull request #16
Opened 2024-03-26 20:50 UTC by bbollen23

Closes #10 , #15

Large updates to the documentation.
1. Added two explicit tutorials for users to walk through
2. Updated structure
3. Examples of individual components will be moved to the type doc pages
4. Added firebase storage set up

2024-03-27 00:30 UTC, JackWilb requested changes

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +The reVisit project is open-source – meaning anyone can see the entire codebase. Most of the work that is done to create a new study is done by making changes to this codebase. Because of this, we wi
```suggestion
The reVISit project is open-source – meaning anyone can see the entire codebase. Most of the work that is done to create a new study is done by making changes to this codebase. Because of this, we will start by “forking the repository”.
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +You should see a “fork” button on the same row as the name of the repository. When you fork a repository, you are essentially creating your own copy of the repository in your GitHub account. This mea
```suggestion
You should see a “fork” button on the same row as the name of the repository. When you fork a repository, you are essentially creating your own copy of the repository in your GitHub account. This means that any changes you commit and push to this new repository will not affect the main source code. Instead, you or your organization will be able to have a central location for all of your studies. 
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +Once you fork the repository, you will be prompted for some basic information about this repository (such as the desired name). After this, you’ll need to clone the repository onto your local machine
This is a bit brief

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +**Step 3: . Once this is finished, you can now start the program:**
```suggestion
**Step 3: Once this is finished, you can now start the program:**
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +This will launch a local server which can be accessed to view and interact with reVisit. By default, you can access this by visiting http://localhost:8080/. Any change you make to the existing codeba
```suggestion
This will launch a local server which can be accessed to view and interact with reVISit. By default, you can access this by visiting http://localhost:8080/. Any change you make to the existing codebase will automatically update the front end.
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +        It is easiest to perform the following tutorial with an IDE. We suggest something like VSCode.
```suggestion
        It is easiest to perform the following tutorial with an IDE. We suggest something like VSCode since it has JSON autocomplete.
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +        "helpTextPath": "basic-questionnaire-study/help.md",
```suggestion
        "helpTextPath": "basic-questionnaire-study/assets/help.md",
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +        "logoPath": "assets/revisitLogoSquare.svg",
```suggestion
        "logoPath": "revisitAssets/revisitLogoSquare.svg",
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +            "path": "basic-questionnaire-study/introduction.md",
```suggestion
            "path": "basic-questionnaire-study/assets/introduction.md",
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +                },
```suggestion
                    "placeholder": "Please enter your first name"
                },
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +Now, if you start the server (using `yarn serve` as described in the Installation section), you'll be able to navigate to "http://localhost:8080/" and view your study in the list of studies. Alternat
```suggestion
Now, if you start the server (using `yarn serve` as described in the <a href="#installation">Installation</a> section), you'll be able to navigate to "http://localhost:8080/" and view your study in the list of studies. Alternatively, you can navigate to "http://localhost:8080/basic-questionnaire-study" to enter the study directly.
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +The HTML code below uses the extensive D3.js library. It renders a simple, horizontal bar chart. Copy and paste this HTML into a document called “bar-chart.html” in the “basic-questionnaire-study” di
```suggestion
The HTML code below uses the extensive D3.js library. It renders a simple, horizontal bar chart. Copy and paste this HTML into a document called “bar-chart.html” in the “basic-questionnaire-study/assets” directory.
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +            "path": "basic-questionnaire-study/bar-chart.html",
```suggestion
            "path": "basic-questionnaire-study/assets/bar-chart.html",
```

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +</div>
Can we make an issue to delete this once it works as it should?

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +reVISit is inherently a serverless program. Because of this, we set up a storage engine in order to store the data that is gathered from users as they move through the study. While you can test the p
We should mention the word "deploy" here and link it to some general deployment section

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +Once that is finished, we'll have to use Google's `gsutil` function in the terminal to set up a CORS policy so that the application can communicate with Firebase storage. Follow <a href="https://clou
Is gsutil still the best way?

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +Now you can navigate to http://localhost:8080 and launch any demo study. All data from any participation will automatically be uploaded to the store.
A study designer would need to change the `.env` file, too

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
> +Deploying your study should be relatively simple. We include a GitHub action that will build your study and deploy it to GitHub pages. Once your configuration is built, you need only push your change
This is missing information about the `PUBLIC_PATH` variable, which needs to be set to `/<repo-name>/`

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
>  Since reVISit uses Firebase as its data store, you can use the Firebase console to download your data. Additionally, we provide the ability to manually download your data from the study ending page.
Let's push people away from manually interacting with firebase/etc.

2024-03-27 00:30 UTC, JackWilb commented on tutorials.md
>  Since reVISit uses Firebase as its data store, you can use the Firebase console to download your data. Additionally, we provide the ability to manually download your data from the study ending page.
This will change as we fix up the tidy downloader, and the download participants buttons. So we can leave as is for now, but maybe we should open up an issue

2024-03-27 15:49 UTC, bbollen23 commented on tutorials.md
> +Once that is finished, we'll have to use Google's `gsutil` function in the terminal to set up a CORS policy so that the application can communicate with Firebase storage. Follow <a href="https://clou
I looked into this and found that this is the only way unfortunately:
https://stackoverflow.com/questions/75514990/why-cant-i-set-a-cors-policy-to-my-firebase-storage-bucket-through-the-google-c

2024-03-27 15:50 UTC, bbollen23 commented on tutorials.md
> +Deploying your study should be relatively simple. We include a GitHub action that will build your study and deploy it to GitHub pages. Once your configuration is built, you need only push your change
Let's talk about this. I moved information from the previous section but hadn't had a chance to look this over.

2024-03-27 15:51 UTC, bbollen23 commented on tutorials.md
>  Since reVISit uses Firebase as its data store, you can use the Firebase console to download your data. Additionally, we provide the ability to manually download your data from the study ending page.
Yeah, let's walk through together how it currently can be done without interacting with Firebase and I can update this portion.

2024-03-27 16:08 UTC, bbollen23 commented on tutorials.md
> +</div>
Made the issue: https://github.com/revisit-studies/reVISit-studies.github.io/issues/17

2024-03-27 21:00 UTC, JackWilb commented on tutorials.md
> +
Test comment for 5 lines

2024-03-28 19:58 UTC, bbollen23 commented on tutorials.md
> +Deploying your study should be relatively simple. We include a GitHub action that will build your study and deploy it to GitHub pages. Once your configuration is built, you need only push your change
Fixed in commit [8ad4bdc](https://github.com/revisit-studies/reVISit-studies.github.io/pull/16/commits/8ad4bdceafd10cb09f3bb6d545a069e7325e115a)

2024-03-28 19:58 UTC, bbollen23 commented on tutorials.md
>  Since reVISit uses Firebase as its data store, you can use the Firebase console to download your data. Additionally, we provide the ability to manually download your data from the study ending page.
Fixed in commit [608c429](https://github.com/revisit-studies/reVISit-studies.github.io/pull/16/commits/608c429a1b6b1995732e4dbfed64040f145de7f4)

2024-03-28 20:02 UTC, bbollen23 commented on tutorials.md
> +reVISit is inherently a serverless program. Because of this, we set up a storage engine in order to store the data that is gathered from users as they move through the study. While you can test the p
Fixed in commit [082bf1d](https://github.com/revisit-studies/reVISit-studies.github.io/pull/16/commits/082bf1dc3dad2ecdf62913ce47383b488cf7de2b)

2024-03-28 20:03 UTC, bbollen23 commented on tutorials.md
> +Now you can navigate to http://localhost:8080 and launch any demo study. All data from any participation will automatically be uploaded to the store.
Fixed in commit [082bf1d](https://github.com/revisit-studies/reVISit-studies.github.io/pull/16/commits/082bf1dc3dad2ecdf62913ce47383b488cf7de2b)

2024-03-28 20:03 UTC, bbollen23 commented on tutorials.md
> +Once you fork the repository, you will be prompted for some basic information about this repository (such as the desired name). After this, you’ll need to clone the repository onto your local machine
Fixed in commit [ecf3ca4](https://github.com/revisit-studies/reVISit-studies.github.io/pull/16/commits/ecf3ca41b9d29dca8f742f327b7b8baa8860706d)

2024-03-29 16:40 UTC, JackWilb requested changes
Some small changes, but everything is looking great

2024-03-29 16:40 UTC, JackWilb commented on tutorials.md
> +<pre><code class="language-markdown"># Introduction
Can we use ``` code block instead of html ones?

2024-03-29 16:40 UTC, JackWilb commented on tutorials.md
> +```
```suggestion
```


```

2024-03-29 16:40 UTC, JackWilb commented on tutorials.md
> +reVISit is inherently a serverless program. Because of this, we set up a storage engine in order to store the data that is gathered from users as they move through the study. While you can test the p
```suggestion
reVISit is inherently a serverless program. Because of this, we set up a storage engine in order to store the data that is gathered from users as they move through the study. While you can test the program locally without any storage, you will need to set up some sort of storage in order to save study participant data. Our intention is that those who create the study have full control over the data that is generated by participants -- no data is ever linked back to the reVISit repository or those who have contributed to its creation. See the <a href="#deploying-to-a-static-website">Deployment</a> section for more information about deploying your study to GitHub.io once the connection to Firebase has been set up. 
```

2024-03-29 16:40 UTC, JackWilb commented on tutorials.md
> +The last step is to enable firebase storage. Open up the `.env` file in the root of the repository. Change the `VITE_STORAGE_ENGINE variable to "firebase". Now you can call `yarn serve` to launch the
```suggestion
The last step is to enable firebase storage. Open up the `.env` file in the root of the repository. Change the `VITE_STORAGE_ENGINE variable to "firebase". Now you can call `yarn serve` to launch the server and navigate to http://localhost:8080 to launch any demo study. All data from any participation will automatically be uploaded to the store. Note: when running `yarn build`, reVISit automatically uses the firebase storage engine.
```

2024-03-29 16:40 UTC, JackWilb commented on tutorials.md
> +Deploying your study should be relatively simple. We include a GitHub action that will build your study and deploy it to GitHub pages. The only item that the user must adjust is in the `.env` file in
```suggestion
Deploying your study should be relatively simple. We include a GitHub action that will build your study and deploy it to GitHub pages. The only item that the user must adjust is in the `.env` file in the root of the repository. At the top of this file, you should see `VITE_BASE_PATH="/study/"`. Change "/study/" to "/<repo-name>/".
```

2024-03-29 16:40 UTC, JackWilb commented on tutorials.md
> +## Deploying to a static website
This is missing some steps. We need to walk a study designer through how to enable GitHub pages for their forked repo. It's only a couple of steps, but will confuse people if it's absent

2024-03-29 16:40 UTC, JackWilb commented on tutorials.md
> +Each key in answer will be labeled the same as the component that it refers to. The sequence is the given sequence that the user saw all components (since these may be different for each participant
```suggestion
Each key in answer will be labeled the same as the response component that it refers to. The sequence shows the order that the participant saw each component (since these may be different for each participant if the configuration sequence has some randomization). This answer wil contain information such as the start time, the end time, and all of the window events. See the example below.
```

2024-03-29 16:40 UTC, JackWilb commented on tutorials.md
> +All times are in **epoch milliseconds**. We can see at a high level that we are given the answer that the user submitted, the start time for the component, and the end time. In addition to this, we h
```suggestion
All times are in **epoch milliseconds**. We can see at a high level that we are given the answer that the user submitted, the start time for the component, and the end time. In addition to this, we have a list of window events. Each item in the window event is given a time, a position an event name, and some extra information for the event (for mouse events, this is the location).
```

2024-03-29 16:40 UTC, JackWilb commented on tutorials.md
> +Since reVISit uses Firebase as its data store, you can use the Firebase console to download your data. Additionally, we provide the ability to manually download your data from the study ending page.
```suggestion
```

2024-03-29 17:01 UTC, bbollen23 commented on tutorials.md
> +<pre><code class="language-markdown"># Introduction
yes, actually. There are some nuances where this isn't possible (like if this was already wrapped in an "info-panel" div tag), but here we can change this.

2024-03-29 17:17 UTC, bbollen23 commented on tutorials.md
> +<pre><code class="language-markdown"># Introduction
Edit: I was wrong. When using ```markdown``` , for some reason it was not detecting that it was markdown and instead thinking that it was CSS. This was a simple way to override that using highlight.js clases.

2024-03-29 22:54 UTC, JackWilb reviewed
Some small grammar fixes

2024-03-29 22:54 UTC, JackWilb commented on tutorials.md
> +With the app set up, we are ready to copy over the app configuration to your revisit project. In image below you will see a JSON object denoted as `const firebase = { ... }`.
``` suggestion
With the app set up, we are ready to copy over the app configuration to your revisit project. In the image below you will see a JSON object denoted as `const firebase = { ... }`.
```

2024-03-29 22:54 UTC, JackWilb commented on tutorials.md
> +The important part here is filling out the domains that you will allow to access the firebase database. Add localhost and 127.0.0.1 to test your survey on your local server.
``` suggestion
The important part here is filling out the domains that you will allow to access the firebase database. Add localhost and 127.0.0.1 to test your survey on your local machine.
```

2024-03-29 22:54 UTC, JackWilb commented on tutorials.md
> +You should now see a SITE KEY and a SECRET Key. First, copy the secret key and paste it back into the Firebase re-captcha page as shown in the following images.
KEY and Key, we should be consistent

2024-03-29 22:54 UTC, JackWilb commented on tutorials.md
> +Now, copy the SITE key. That site should now go back into your `.env` file for the variable `VITE_RECAPTCHAV3TOEKN`.
key, here. Should be consistent with above

2024-04-01 16:38 UTC, JackWilb approved these changes

2024-04-01 16:39 UTC, merged